version: "3"
services:
  app:
    image: yt8492/snorlax:latest
    container_name: "snorlax-app"
    ports:
      - "3000:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_URL: ${S3_URL}
